# Generated by Django 3.2.9 on 2021-12-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Chiqim summasi')),
                ('descriptions', models.TextField(verbose_name="Ma'lumot")),
                ('data', models.DateField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chiqimlar',
                'verbose_name_plural': 'Chiqim',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kirim summasi')),
                ('descriptions', models.TextField(verbose_name="Ma'lumot")),
                ('data', models.DateField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kirimlar',
                'verbose_name_plural': 'Kirim',
            },
        ),
    ]
