# Generated by Django 3.2.9 on 2021-11-30 18:21

from django.db import migrations, models
import django.db.models.deletion
import productapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategoriya')),
                ('date', models.CharField(max_length=32)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('parametr', models.CharField(choices=[('metr', 'metr'), ('dona', 'dona'), ('kg', 'kg')], max_length=32, verbose_name='Mahuslot birligi')),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=productapp.models.upload_file_name, verbose_name='Mahsulot rasmi')),
                ('qr', models.CharField(max_length=255, verbose_name='Q/R')),
                ('amount', models.FloatField(verbose_name='Mahsulot miqdori')),
                ('sel_price', models.FloatField(verbose_name='Olingan narx')),
                ('finish_price', models.FloatField(verbose_name='Sotiladigan oxirgi narx')),
                ('date', models.CharField(max_length=32, verbose_name="Mahsulot qo'shilgan vaqt")),
                ('descriptions', models.TextField(verbose_name="Mahsulot haqida ma'lumot")),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productapp.category', verbose_name='Kategoriya nomi')),
            ],
        ),
    ]
