# Generated by Django 3.2.9 on 2021-12-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterField(
            model_name='customer',
            name='descriptions',
            field=models.TextField(verbose_name="Mijoz haqida ma'lumot"),
        ),
    ]
